version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-nodejs
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: root
      MYSQL_PASSWORD: ''

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-nodes-network

  nodejs:
    depends_on:
      - db
    image: node
    ports:
      - "3000:3000"
    container_name: nodejs
    restart: unless-stopped
    environment:
       NODE_DB_HOST: db:3307
       NODE_USER: root
       NODE_ROOT_PASSWORD: Mucura$Bob#Tia0
     
    
    networks:
      - mysql-nodes-network
    
volumes: 
  db_data: {}
networks:
  mysql-nodes-network:
    driver: bridge
